In [ ]:
import torch


# Import Class Linear
from torch.nn import Linear

Let us create the following expressions:

$b=-1,w=2$

$\hat{y}=-1+2x$

In [ ]:
# Define w = 2 and b = -1 for y = wx + b

w = torch.tensor(2.0, requires_grad = True)       #later we will learn how to train these parameters
b = torch.tensor(-1.0, requires_grad = True)

In [ ]:
# Function forward(x) for prediction

def forward(x):
    yhat = w * x + b
    return yhat

In [ ]:
# Predict y = 2x - 1 at x = 1

x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


Now, let us try to make the prediction for multiple inputs:

In [ ]:
x = torch.tensor([[1.0], [2.0]])
# Make the prediction of y = 2x - 1 at x = [1, 2]
yhat = forward(x)
print("The prediction: \n", yhat)

The prediction: 
 tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


<h2 id="Linear">Class Linear</h2>
Let us create the linear object by using the constructor. The parameters are randomly created. Let us print out to see what <i>w</i> and <i>b</i> are.

In [ ]:
# Create Linear Regression Model, and print out the parameters

lr = Linear(in_features=1, out_features=1, bias=True)     #here we are creating an equation of a line
print("Parameters w and b: ", list(lr.parameters()))          #here first is the slope and the second is the bias

Parameters w and b:  [Parameter containing:
tensor([[-0.3171]], requires_grad=True), Parameter containing:
tensor([-0.4382], requires_grad=True)]


In [ ]:

# Make the prediction at x = [[1.0]]

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.7553]], grad_fn=<AddmmBackward>)


Use model <code>lr(x)</code> to predict the result.

In [ ]:
# Create the prediction using linear model

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.7553],
        [-1.0725]], grad_fn=<AddmmBackward>)


<h2 id="Cust">Build Custom Modules</h2>
Now, let's build a custom module using nn.modules . We can make more complex models by using this method later on. 

In [ ]:
from torch import nn

In [ ]:
# Customize Linear Regression Class

class LR(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        
        # Inherit from parent
        super(LR, self).__init__()      #help create object from package nn.Module
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out

In [ ]:
# Create the linear regression model. Print out the parameters.

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))  #we can do this because LR inherit nn.Module
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[0.5649]], requires_grad=True), Parameter containing:
tensor([-0.7678], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [ ]:
# Try our customize linear regression model with single input

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.2030]], grad_fn=<AddmmBackward>)


In [ ]:
# Try our customize linear regression model with multiple input

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.2030],
        [ 0.3619]], grad_fn=<AddmmBackward>)
